# Generated by Django 4.2.7 on 2023-11-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=30)),
                ('Career', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Profile_img', models.ImageField(upload_to='profile/')),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Greetings', models.CharField(max_length=10)),
                ('Home_Copy', models.TextField(blank=True)),
                ('Picture', models.ImageField(upload_to='picture/')),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Name', models.CharField(max_length=25)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_name', models.CharField(max_length=10)),
                ('links', models.URLField()),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.about')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.services')),
            ],
        ),
    ]
