# Generated by Django 4.2.7 on 2023-11-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_about_career_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Icon',
            field=models.CharField(default='bx bx-code-alt', max_length=20),
            preserve_default=False,
        ),
    ]
