# Generated by Django 4.2.7 on 2023-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Icon',
            field=models.CharField(max_length=40),
        ),
    ]
