# Generated by Django 4.2.7 on 2023-11-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_home_socialmedia_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Social_Icon',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
