# Generated by Django 4.2.7 on 2023-11-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_home_social_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='SocialMedia_links',
        ),
        migrations.RemoveField(
            model_name='home',
            name='Social_Icon',
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Socialmedia_Url', models.URLField(blank=True)),
                ('Social_Icon', models.CharField(blank=True, max_length=45)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.home')),
            ],
        ),
    ]
