# Generated by Django 4.2.7 on 2023-11-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_socialmedia_social_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='cv_pdf/')),
            ],
        ),
    ]
